# Generated by Django 4.0.1 on 2024-07-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
