# Generated by Django 4.0.1 on 2024-07-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_is_staff_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
